@Address=https://localhost:7240/api/Consumer
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IkNPTlNVTUVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJhOTJiM2U3YS01Nzk4LTQ1YmUtYWM3NC1iZGZjNmVjZDY1MmIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjb25zdW1lckBkZWFsc2hpZWxkLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkNvbnN1bWVyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkRlYWxTaGllbGQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9tb2JpbGVwaG9uZSI6Ijk4NjUyNjI2MjYiLCJleHAiOjE3MjY2NTA0MDksImlzcyI6IkRyYWdvbnNFc2Nyb3ciLCJhdWQiOiJEcmFnb25zRXNjcm93In0.6eBldifGlJ8X2neSRFIlHel6LWB4gzu2irdFGlV5gsI

POST {{Address}}/register
Content-Type: application/json

{
  "firstName": "Sajal",
  "lastName": "Ghimire",
  "email": "test@consumer.com",
  "phone": "1234567890",
  "password": "Ab@12abc"
}

####### Login as consumer
POST {{Address}}/login
Content-Type: application/json

{
  "email": "consumer@dealshield.com",
  "password": "F@kepassword1111"
}

######### GET ALL CONSUMERS ORDER
GET {{Address}}/GetAllOrder
Authorization: Bearer {{Token}}

############ GET DETAIL 
GET {{Address}}/details
Authorization: Bearer {{Token}}


########

GET {{Address}}/hello