@Address=https://localhost:7240/api/Consumer
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IkNPTlNVTUVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxZjhhNzYyOS1kNmIzLTQwZTQtYjZkOC1kMzc5M2RjOGNmOGIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBjb25zdW1lci5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTYWphbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJHaGltaXJlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiI5ODQ1MjA5MDgwIiwiZXhwIjoxNzI1NDMxOTgxLCJpc3MiOiJEcmFnb25zRXNjcm93IiwiYXVkIjoiRHJhZ29uc0VzY3JvdyJ9.I7J--5-eWwCcZbuXa56N3NThKlVqwI6IVcPJzX7UstQ

POST {{Address}}/register
Content-Type: application/json

{
  "firstName": "Sajal",
  "lastName": "Ghimire",
  "email": "test@consumer.com",
  "phone": "1234567890",
  "password": "Ab@12abc"
}

####### Login as consumer
POST {{Address}}/login
Content-Type: application/json

{
  "email": "sajal@consumer.com",
  "password": "F@kepassword1618"
}

######### GET ALL CONSUMERS ORDER
GET {{Address}}/GetAllOrder
Authorization: Bearer {{Token}}

############ GET DETAIL 
GET {{Address}}/details
Authorization: Bearer {{Token}}


########

GET {{Address}}/hello