@Address=https://localhost:7240/api/Order
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IkNPTlNVTUVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI4ZTdjMTcwNy05N2Y3LTRkZTgtODE2Yi0wZmZkZWZkNmU5MTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTYWphbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJHaGltaXJlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIxMjM0NTY3ODkwIiwiZXhwIjoxNzA0NjE4NzY3LCJpc3MiOiJEcmFnb25zRXNjcm93IiwiYXVkIjoiRHJhZ29uc0VzY3JvdyJ9.rHLx0jtavrpHiu0yAESvcsYC4fppHTJdAsLqWYHph0c
@ProviderToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlBST1ZJREVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI1MGRlMmZhMS1iN2ZkLTQyMDAtOTliZS03OGRiMGI2YTZmZTciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbDFAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiU2FqYWwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR2hpbWlyZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL21vYmlsZXBob25lIjoiMTIzNDU2Nzg5MCIsImV4cCI6MTcwNDAxNDQ1NiwiaXNzIjoiRHJhZ29uc0VzY3JvdyIsImF1ZCI6IkRyYWdvbnNFc2Nyb3cifQ._7kSOnl2nkvsFYGaEDV3cz6lZpqI_8uksATdLIUD3hM
@OrderId=6ddcd168-477a-4d12-9d51-1e18bb5d5484

POST {{Address}}/create
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "Name": "Tile my kitchen floor",
    "Description": "Kitchen is 10x10 square foot. Want white tiles. Should cover all 4 walls. Must be highest quality tiles",
    "AllowedDays": 7,
    "Cost": 4500
}

############ Order detail
GET {{Address}}/{{OrderId}}
Authorization: Bearer {{Token}}

########### Accept order - need providerId
GET {{Address}}/Accept/{{OrderId}}
Authorization: Bearer {{ProviderToken}}

########## Accept bid
GET {{Address}}/{{OrderId}}/AcceptBid?BidId=9fc6c8fc-aa21-4160-959f-aeedf061cd87
Authorization: Bearer {{Token}}
