@Address=https://localhost:7240/api/Order
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IkNPTlNVTUVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyY2Y0YWM0YS1lYTdkLTQ2YTEtYTEwOS0wMzRiY2Y3OGVkMjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTYWphbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJHaGltaXJlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIxMjM0NTY3ODkwIiwiZXhwIjoxNzA0ODAwMTE0LCJpc3MiOiJEcmFnb25zRXNjcm93IiwiYXVkIjoiRHJhZ29uc0VzY3JvdyJ9.G3UmrL46Rq1FwaIyTOW5WEP-4-p9slCpavUwTrGy2tQ
@OrderId=5bccc611-615a-4e8c-91d9-c20a7cdc6cbf

POST {{Address}}/create
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "Name": "Tile my kitchen floor",
    "Description": "Kitchen is 10x10 square foot. Want white tiles. Should cover all 4 walls. Must be highest quality tiles",
    "AllowedDays": 7,
    "Cost": 4500
}

############ Order detail
GET {{Address}}/{{OrderId}}
Authorization: Bearer {{Token}}

########## Accept bid
GET {{Address}}/{{OrderId}}/AcceptBid?BidId=09143586-1080-487f-af7f-830dbba96be5
Authorization: Bearer {{Token}}