@Address=https://localhost:7240/api/Provider
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlBST1ZJREVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIzMDJmMWJkZS1kNGE1LTRlMjAtYWNkOC1hN2QzNWEzMWI5MDMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbDExQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IlNhamFsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkdoaW1pcmUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9tb2JpbGVwaG9uZSI6IjEyMzQ1Njc4OTAiLCJleHAiOjE3MDQ2MTk0MDMsImlzcyI6IkRyYWdvbnNFc2Nyb3ciLCJhdWQiOiJEcmFnb25zRXNjcm93In0.5DbAce6xGCXXBSTk0ff741syTFKd8vBYrgD1Esswj44


POST {{Address}}/register
Content-Type: application/json

{
  "firstName": "Sajal",
  "lastName": "Ghimire",
  "email": "sajal11@gmail.com",
  "phone": "1234567890",
  "password": "Abc@@12abc"
}

####### Login as consumer
POST {{Address}}/login
Content-Type: application/json

{
  "email": "sajal1@gmail.com",
  "password": "Abc@@12abc"
}

###### Create a bid
POST {{Address}}/CreateBid
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "OrderId": "5a35efb3-03eb-442d-b22b-99eb6779d03f",
    "ProposedAmount": 300000,
    "Comment": "Will use certified A-One materials."
}