@Address=https://localhost:7240/api/Provider
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlBST1ZJREVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI5NzRlMTFlNi1kZWJiLTRlMTUtYWRjNi1hZWFkZjRiNTFjZjciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBwcm92aWRlci5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJTYWphbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJHaGltaXJlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiI5ODQ1MjA5MDgwIiwiZXhwIjoxNzI1NTk4NjUzLCJpc3MiOiJEcmFnb25zRXNjcm93IiwiYXVkIjoiRHJhZ29uc0VzY3JvdyJ9.3PhTEteWlPcXDXkbz9tde27EJGmfoaweqg1lilHImbs

POST {{Address}}/register
Content-Type: application/json

{
  "firstName": "Sajal",
  "lastName": "Ghimire",
  "email": "test@provider.com",
  "phone": "1234567890",
  "password": "Abc@@12abc"
}

####### Login as provider
POST {{Address}}/login
Content-Type: application/json

{
  "email": "sajal@provider.com",
  "password": "F@kepassword1618"
}

##### Provider detail
GET {{Address}}/details
Authorization: Bearer {{Token}}

###### Create a bid
POST {{Address}}/CreateBid
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "OrderId": "4038da71-ddac-498f-8c62-daf9670f4c1f",
    "ProposedAmount": 2000,
    "Comment": "Will be using A1 materials."
}


#### Get All Selected bids
GET {{Address}}/GetSelectedBids
Authorization: Bearer {{Token}}

### Generate Khalti payment Uri

POST https://a.khalti.com/api/v2/epayment/initiate/
Content-Type: application/json
Authorization: key live_secret_key_68791341fdd94846a146f0457ff7b455

{
  "return_url": "https://docs.khalti.com/khalti-epayment/",
  "website_url": "https://example.com/",
  "amount": "1000",
  "purchase_order_id": "Order01",
  "purchase_order_name": "test",
  "customer_info": {
    "name": "Test Bahadur",
    "email": "test@khalti.com",
    "phone": "9800000001"
  }
}

############ Provider public detail
GET {{Address}}/providerDetails/36597a2a-199a-40a6-8d65-b90bf8611dd7

