@Address=https://localhost:7240/api/Provider
@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlBST1ZJREVSIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiM2E2ZDU2YS1mMDcyLTRiNjctYjdhNC00ZGQ0NDQyYzNmMDYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbHVqMTFAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiU2FqYWwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiR2hpbWlyZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL21vYmlsZXBob25lIjoiMTIzNDU2Nzg5MCIsImV4cCI6MTcwNDgwMDcyMywiaXNzIjoiRHJhZ29uc0VzY3JvdyIsImF1ZCI6IkRyYWdvbnNFc2Nyb3cifQ.onAzMxWcqe8lX8lV7wyuLpN7blJyPuveHz3lkRU0UUk

POST {{Address}}/register
Content-Type: application/json

{
  "firstName": "Sajal",
  "lastName": "Ghimire",
  "email": "sajaluj11@gmail.com",
  "phone": "1234567890",
  "password": "Abc@@12abc"
}

####### Login as consumer
POST {{Address}}/login
Content-Type: application/json

{
  "email": "sajaluj@gmail.com",
  "password": "Abc@@12abc"
}

###### Create a bid
POST {{Address}}/CreateBid
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "OrderId": "5bccc611-615a-4e8c-91d9-c20a7cdc6cbf",
    "ProposedAmount": 300000,
    "Comment": "Will be using A1 materials."
}